spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.136.198.217/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 10.136.198.41
    port: 6379
wechat:
    mpAppid:11111111
    mpAppSecret:111111111111
